$(function(){
	$(".hc-div-cate1").mouseover(function(){
		$(this).hide();
		$(".hc-div1").fadeIn();
		});
	$(".hc-div1").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate1").show();
		});
	$(".hc-div-cate2").mouseover(function(){
		$(this).hide();
		$(".hc-div2").fadeIn();
		});
	$(".hc-div2").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate2").show();
		});
	$(".hc-div-cate3").mouseover(function(){
		$(this).hide();
		$(".hc-div3").fadeIn();
		});
	$(".hc-div3").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate3").show();
		});
	$(".hc-div-cate4").mouseover(function(){
		$(this).hide();
		$(".hc-div4").fadeIn();
		});
	$(".hc-div4").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate4").show();
		});
	$(".hc-div-cate5").mouseover(function(){
		$(this).hide();
		$(".hc-div5").fadeIn();
		});
	$(".hc-div5").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate5").show();
		});
	$(".hc-div-cate6").mouseover(function(){
		$(this).hide();
		$(".hc-div6").fadeIn();
		});
	$(".hc-div6").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate6").show();
		});
	$(".hc-div-cate7").mouseover(function(){
		$(this).hide();
		$(".hc-div7").fadeIn();
		});
	$(".hc-div7").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate7").show();
		});
	$(".hc-div-cate8").mouseover(function(){
		$(this).hide();
		$(".hc-div8").fadeIn();
		});
	$(".hc-div8").mouseleave(function(){
		$(this).hide();
		$(".hc-div-cate8").show();
		});	
});